name: Publish to Test.PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: ''
        description: "poetry version"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    # Limit branch:
    if: github.ref == 'refs/heads/dev'
    # Or
    #if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Inputs
        uses: Payadel/inputs@v0.2.3
        id: inputs
        with:
          inputs: |
            - name: version
              default: ''
            - name: current-branch-name
              default: '$(git rev-parse --abbrev-ref HEAD)'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Update poetry version
        run: |
          poetry version ${{ steps.inputs.outputs.version }}
        if: ${{ steps.inputs.outputs.version != '' }}

      - name: Configure poetry
        env:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi __token__ $pypi_token

      - name: Build and publish
        run: |
          poetry build 
          poetry publish -r testpypi 
