name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: ''
      ignore-same-version-error:
        type: boolean
        required: false
        default: false
      ignore-less-version-error:
        type: boolean
        required: false
        default: false
      create-pr-for-branch:
        required: false
        default: ''
        description: Target branch? empty for skip.
      generate-changelog:
        type: choice
        default: auto
        options:
          - never
          - always
          - auto
      release-file-name:
        required: false
        default: 'release'

permissions:
  contents: write
  pull-requests: write

jobs:
  default:
    runs-on: ubuntu-latest

    # Limit branch:
    if: github.ref == 'refs/heads/dev'
    # Or
    #if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Inputs
        uses: payadel/inputs@v0.2.3
        id: inputs
        with:
          inputs: |
            - name: version
              default: ''
            - name: ignore-same-version-error
              default: 'false'
            - name: ignore-less-version-error
              default: 'false'
            - name: create-pr-for-branch
              default: ''
            - name: generate-changelog
              default: 'auto'
            - name: release-file-name
              default: 'release'
            - name: current-branch-name
              default: '$(git rev-parse --abbrev-ref HEAD)'

      - name: Release
        uses: Payadel/release-sv-action@v0.3.1
        id: release
        with:
          version: ${{ steps.inputs.outputs.version }}
          ignore-same-version-error: ${{ steps.inputs.outputs.ignore-same-version-error }}
          ignore-less-version-error: ${{ steps.inputs.outputs.ignore-less-version-error }}
          create-pr-for-branch: ${{ steps.inputs.outputs.create-pr-for-branch }}
          generate-changelog: ${{ steps.inputs.outputs.generate-changelog }}
          skip-release-file: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print outputs
        run: |
          echo "version: ${{ steps.release.outputs.version }}"
          echo "pull-request-url: ${{ steps.release.outputs.pull-request-url }}"
          echo "release-filename: ${{ steps.release.outputs.release-filename }}"

      - name: Update poetry version
        run: |
          pip install poetry
          poetry version ${{ steps.release.outputs.version }}
          git add pyproject.toml
          git commit -m "chore: update pyproject to ${{ steps.release.outputs.version }}"
          git push

      - name: Build poetry
        run: |
          poetry build
          mv 'dist/package_name-${{ steps.release.outputs.version }}.tar.gz' 'dist/${{ steps.release.outputs.release-filename }}.tar.gz'

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/${{ steps.release.outputs.release-filename }}.tar.gz'
          allowUpdates: true
          body: ${{ steps.release.outputs.changelog }}
          tag: 'v${{ steps.release.outputs.version }}'