log:
  stream:
    level: 'info'
    format: '[%(levelname)s] %(message)s'
  file:
    disable: True
    level: 'debug'
    file_name: 'app.log'
    format: '%(asctime)s [%(levelname)s] %(message)s'
proxy:
  disable: True
  host: '127.0.0.1'
  port: 9050