# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
      # args: [ "--check", "package_name" ]

  - repo: https://github.com/PyCQA/pylint/
    rev: v2.14.5
    hooks:
      - id: pylint
        exclude: tests/  # Prevent files in tests/ to be passed in to pylint.

  - repo: https://github.com/Payadel/pre-commit-hooks
    rev: v0.1.2
    hooks:
#      - id: run-scripts
#        name: check-tox-before-push
#        args: [ "-f=.hooks/check-tox.sh", "dev" ]
#        stages: [ push ]
#        pass_filenames: false
#        verbose: false
      - id: run-scripts
        name: check-pytest-before-push
        args: [ "-f=.hooks/check-pytest.sh", "--disable-pytest-warnings" ]
        stages: [ push ]
        pass_filenames: false
        verbose: false
